{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gbcraft",
    "module": "tyroparty",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vaokrg73hrgule7lrbazb2narm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tyroparty-2.0.0.jar",
          "url": "tyroparty-2.0.0.jar",
          "size": 24914,
          "sha512": "a32c665bd87a79f873091395862676cf005e3d1474ee8d272667db40714913c7fe288e8a5d24d02dc7e0d86ea59e6ca2366c94ed34a0642cc4ecd470107ab219",
          "sha256": "54553e67ab0efa77b2999c1505186c419e8c041b9772ff2b67e8b5884beffa94",
          "sha1": "6a29b60b624e0aa92fe5eedf631a6efb330fbda7",
          "md5": "b4b1ddd0e92c26f0653b6ee0c4d5f24a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tyroparty-2.0.0.jar",
          "url": "tyroparty-2.0.0.jar",
          "size": 24914,
          "sha512": "a32c665bd87a79f873091395862676cf005e3d1474ee8d272667db40714913c7fe288e8a5d24d02dc7e0d86ea59e6ca2366c94ed34a0642cc4ecd470107ab219",
          "sha256": "54553e67ab0efa77b2999c1505186c419e8c041b9772ff2b67e8b5884beffa94",
          "sha1": "6a29b60b624e0aa92fe5eedf631a6efb330fbda7",
          "md5": "b4b1ddd0e92c26f0653b6ee0c4d5f24a"
        }
      ]
    }
  ]
}
