{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gbcraft",
    "module": "tyroparty",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kis6e6hhqbeq5b42urnurqtuku"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tyroparty-2.0.0.jar",
          "url": "tyroparty-2.0.0.jar",
          "size": 24835,
          "sha512": "f11e32cfabccd206358b0a149ed38c2171864f4d7ac1b0d5b3368082f44f035fb07e55e3e4992e282e93b1974957fa37725674892659cfdaebafeebc8f448225",
          "sha256": "48703d624d37251c224c76e9470a508da3024692efc5822bbd589f3a7bab8548",
          "sha1": "c66896cf2eaaddbdf98a6e1ce59029bc31e9c27d",
          "md5": "7ed2c519ce0c7f0a77f6f22caf1bb8bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tyroparty-2.0.0.jar",
          "url": "tyroparty-2.0.0.jar",
          "size": 24835,
          "sha512": "f11e32cfabccd206358b0a149ed38c2171864f4d7ac1b0d5b3368082f44f035fb07e55e3e4992e282e93b1974957fa37725674892659cfdaebafeebc8f448225",
          "sha256": "48703d624d37251c224c76e9470a508da3024692efc5822bbd589f3a7bab8548",
          "sha1": "c66896cf2eaaddbdf98a6e1ce59029bc31e9c27d",
          "md5": "7ed2c519ce0c7f0a77f6f22caf1bb8bd"
        }
      ]
    }
  ]
}
